### PR TITLE
Python 3 compatiblity for urllib

### PR DESCRIPTION
**Pull request by knkarthik**
Python 3 the "urllib.request" is a module by itself

### CODE REVIEW

**Comment by brentp** [comment]
Thanks for the PR.
this breaks python2 compat, right?
I'm fine with the change as long as it incorporates a check like

```
try:
    from urllib.request import urlopen
except ImportError:
    from urllib import urlopen
```

can you add a test?

**Comment by iskandr** [comment]
Not sure if you all have discussed this before, but I recommend using [six](https://pypi.python.org/pypi/six) for py2 vs. py3 differences:
```
from six.moves.urllib.request import urlopen
```

**Comment by knkarthik** [comment]
Thanks @iskandr for pointing out `six`. I guess using `six` makes sense since it is already being used elsewhere in this project. I've updated the code accordingly. @brentp Looks OK?

**Comment by brentp** [comment]
with the latest change you;ll have to add six to the requirements. I'd prefer just to use the try/except to avoid the dependency unless we use six throughout cruzdb.

**Comment by brentp** [comment]
ok. I see the `six

**Comment by brentp** [comment]
ok. I see that six is already a requirement. can you add a test for this?

**Comment by knkarthik** [comment]
OK, I've added a check.

**Comment by brentp** [comment]
sorry, I meant a test like in `tests/test_db.py`
the try/except shouldn't be needed since six will be available.

**Comment by brentp** [comment]
thanks! is it ready?

**Comment by knkarthik** [comment]
Yes, the test seems to pass

**Comment by brentp** [comment]
thanks for persisting!

**Comment by knkarthik** [comment]
No problem..Thank you for the merge. This is my first PR merge! :smiley:

**Pull request merged**
